name: Patrick Oancia
favicon: null
layout_spectrum: 0.5129
typography_spectrum: 0.60785
title: The Right Way Home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#484143'
    - '#000000'
    - '#8c8889'
    - '#2cc4f4'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
