name: Patrick Oancia
favicon: null
layout_spectrum: 0.6423217337578535
typography_spectrum: 0.09293604595586658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf0f1'
    - '#36303a'
    - '#5d5e63'
    - '#cd9a7f'
    - '#a07a63'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.8455541331786662
  rhythmicContrast: 0.75
purpose: []
